
# services:
#   clickhouse:
#     image: clickhouse/clickhouse-server:latest
#     container_name: clickhouse
#     ports:
#       - "8123:8123"   # HTTP interface (for browser / Tabix)
#       - "9000:9000"   
#       - "9009:9009"   # Optional interserver communication
#     environment:
#       CLICKHOUSE_USER: default
#       CLICKHOUSE_PASSWORD: click123
#       CLICKHOUSE_DB: default
#     volumes:
#       - clickhouse_data:/var/lib/clickhouse
#     ulimits:
#       nofile:
#         soft: 262144
#         hard: 262144

# volumes:
#   clickhouse_data:
